# VDJServer Docker Orchestration

version: '2'

services:
    vdjr-mongo:
        build: ./../../vdjserver-mongodb
        container_name: vdjr-mongo
        expose:
            - "27017"
        image: vdjserver/vdjserver-mongo
        volumes:
            - /vdjZ/mongodb:/data/db
        networks:
            - default
        command: mongod --auth

    vdjr-airr-api:
        build: ./../../api-js-mongodb
        container_name: vdjr-airr-api
        env_file: ./../../api-js-mongodb/.env
        ports:
            - "8080:8080"
        image: vdjserver/api-js-mongodb
        networks:
            - default

networks:
    default:
        driver: bridge
