# VDJServer Docker Orchestration

version: '2'

services:
    vdjr-airr-tapis:
        build: ./../../api-js-tapis
        container_name: vdjr-airr-tapis
        env_file: ./../../api-js-tapis/.env
        ports:
            - "8020:8020"
        image: vdjserver/api-js-tapis
        networks:
            - default

networks:
    default:
        driver: bridge
