# VDJServer Docker Orchestration

services:
    vdjr-airr-tapis:
        build: ./../../adc-api-js-tapis
        container_name: vdjr-airr-tapis
        env_file: ./../../.env
        ports:
            - "8020:8020"
            - "8021:8021"
        image: vdjserver/adc-api-js-tapis
        networks:
            - default
        volumes:
            - ./../../adc-api-js-tapis/redis:/api-js-tapis/redis
            - /vdjZ:/vdjZ

    vdjr-stats-tapis:
        build: ./../../stats-api-js-tapis
        container_name: vdjr-stats-tapis
        env_file: ./../../.env
        ports:
            - "8025:8025"
        image: vdjserver/stats-api-js-tapis
        networks:
            - default
        volumes:
            - ./../../stats-api-js-tapis/redis:/stats-api-js-tapis/redis

networks:
    default:
        driver: bridge
