# VDJServer Docker Orchestration

version: '2'

services:
    vdjr-mongo:
        build: ./../../repository-mongodb
        container_name: vdjr-mongo
        expose:
            - "27017"
        image: ireceptor/repository-mongo
        volumes:
            - /vdjZ/repository/ireceptor/rep02/mongodb:/data/db
        networks:
            - default
        command: mongod --auth

    vdjr-ireceptor-api:
        build: ./../../service-js-mongodb
        container_name: vdjr-ireceptor-api
        env_file: ./../../service-js-mongodb/.env
        ports:
            - "8080:8080"
        image: ireceptor/service-js-mongodb
        networks:
            - default

networks:
    default:
        driver: bridge
